// Shoutbox 1.00 - power
var Shoutbox=jQuery.extend(Shoutbox||{},{toggle:!1,delete_messages:function(a,b){var c=Shoutbox.data[a].room_name;jQuery.post(Shoutbox.ajaxurl,{action:"shoutbox-ajax-delete",to_delete_ids:b,to_delete_room_name:c},function(a){if(a.rows_affected==b.length)for(var e in Shoutbox.data){if(Shoutbox.data[e].room_name==c)for(a=0;"undefined"!=typeof b[a];a++)jQuery("div[data-shoutbox-id="+e+'] input[type=checkbox][value="'+b[a]+'"]').parents(".shoutbox-history-message-alias-container").remove()}else location.reload(!0)})},
clean_messages:function(a){var b=Shoutbox.data[a].room_name;a=jQuery("div[data-shoutbox-id="+a+"] div.shoutbox-history-container");var c=jQuery(a).children().size();c>Shoutbox.clean_target&&jQuery.post(Shoutbox.ajaxurl,{action:"shoutbox-ajax-clean",to_clean_room_name:b},function(a){var e=c-Shoutbox.clean_target;if(a.rows_affected==e)for(var f in Shoutbox.data){if(Shoutbox.data[f].room_name==b){var g=e;for(a=jQuery("div[data-shoutbox-id="+f+"] div.shoutbox-history-container");0<
g;g--)jQuery(a).children(":first").remove()}}else location.reload(!0)})},ban_users:function(a,b){var c=jQuery.find('div[class=shoutbox-container][data-shoutbox-id="'+a+'"]');jQuery.post(Shoutbox.ajaxurl,{action:"shoutbox-ajax-ban",to_ban_ips:b},function(a){jQuery(c).find(".shoutbox-users-container input[type=checkbox]").each(function(){jQuery(this).attr("checked",!1)})})},transcript:function(a){jQuery.post(Shoutbox.ajaxurl,{action:"shoutbox-ajax-transcript",room_name:Shoutbox.data[a].room_name},
function(a){window.open(Shoutbox.stripslashes(a.transcript_url))})}});
jQuery("div.shoutbox-delete-link a").on("click",function(a){a.preventDefault();var b=jQuery(this).parents(".shoutbox-container").attr("data-shoutbox-id"),c=jQuery(this),d=[];jQuery(this).parents(".shoutbox-container").find(".shoutbox-history-container input[type=checkbox]:checked").each(function(){d.push(jQuery(this).val())});jQuery(this).fadeTo(100,0,function(){""==d?alert(Shoutbox.i18n.delete_what_s):confirm(Shoutbox.i18n.delete_confirm_s)&&Shoutbox.delete_messages(b,d);jQuery(c).fadeTo(100,
1)})});jQuery("div.shoutbox-clean-link a").on("click",function(a){a.preventDefault();var b=jQuery(this).parents(".shoutbox-container").attr("data-shoutbox-id"),c=jQuery(this);jQuery(this).fadeTo(100,0,function(){confirm(Shoutbox.i18n.clean_confirm_s.replace("%s",Shoutbox.clean_target))&&Shoutbox.clean_messages(b);jQuery(c).fadeTo(100,1)})});
jQuery("div.shoutbox-ban-link a").on("click",function(a){a.preventDefault();var b=jQuery(this).parents(".shoutbox-container").attr("data-shoutbox-id"),c=jQuery(this),d=[];jQuery(this).parents(".shoutbox-container").find(".shoutbox-users-container input[type=checkbox]:checked").each(function(){d.push(jQuery(this).val())});jQuery(this).fadeTo(100,0,function(){""==d?alert(Shoutbox.i18n.ban_who_s):confirm(Shoutbox.i18n.ban_confirm_s)&&Shoutbox.ban_users(b,d);jQuery(c).fadeTo(100,1)})});
jQuery(document).on("click","div.shoutbox-transcript-link a",function(a){a.preventDefault();var b=jQuery(this).parents(".shoutbox-container").attr("data-shoutbox-id"),c=jQuery(this);jQuery(this).fadeTo(100,0,function(){Shoutbox.transcript(b);jQuery(c).fadeTo(100,1)})});
jQuery("div.shoutbox-select-all-link a").on("click",function(a){a.preventDefault();var b=jQuery(this);jQuery(this).fadeTo(100,0,function(){jQuery(b).parents(".shoutbox-container").find(".shoutbox-history-container input[type=checkbox]").prop("checked",!Shoutbox.toggle);Shoutbox.toggle=!Shoutbox.toggle;jQuery(b).fadeTo(100,1)})});